# Generated by Django 3.2.3 on 2021-05-29 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckSAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('diagram_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sas.checksas')),
            ],
        ),
        migrations.CreateModel(
            name='SubDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('source', models.CharField(max_length=128)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sas.diagram')),
            ],
        ),
        migrations.CreateModel(
            name='Processes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('source', models.CharField(default=None, max_length=128)),
                ('table_name', models.CharField(max_length=128)),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sas.diagram')),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=128)),
                ('physical_name', models.CharField(max_length=128)),
                ('processes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sas.processes')),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=128)),
                ('physical_name', models.CharField(max_length=128)),
                ('processes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sas.processes')),
            ],
        ),
    ]
